#!/usr/bin/with-contenv sh


# Wait database
sleep 5

cat <<EOL
┌───────────────┐
  LARAVEL QUEUE
└───────────────┘
EOL

export QUEUE_WORK_ATTEMPTS=3

cd /var/www/html
# exec s6-setuidgid nginx php artisan queue:work --queue=high,default --tries=${QUEUE_WORK_ATTEMPTS}


for i in $(seq 1 5); do
    exec s6-setuidgid nginx php artisan queue:work --queue=high,default --tries=${QUEUE_WORK_ATTEMPTS} &
done
wait
