#!/usr/bin/with-contenv sh


if [ "$APP_ENV" = "local" ]; then

cat <<EOL
┌────────────────────┐
  VITE BUILD DEVELOP
└────────────────────┘
EOL

    cd /var/www/html
    exec s6-setuidgid nginx npm run dev

fi
